/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    revendedores: RevendedoreAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    produtos: Produto;
    categorias: Categoria;
    banners: Banner;
    campanhas: Campanha;
    posts: Post;
    cases: Case;
    imprensa: Imprensa;
    revendedores: Revendedore;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    campanhas: CampanhasSelect<false> | CampanhasSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    imprensa: ImprensaSelect<false> | ImprensaSelect<true>;
    revendedores: RevendedoresSelect<false> | RevendedoresSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Revendedore | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface RevendedoreAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  /**
   * Comercial, exibido ao cliente. Alfanumerico (ex.: 109, 233 CL).
   */
  codigoSite: string;
  /**
   * Chave de integracao CRM/ERP. NAO e unique: variacoes CL/PB compartilham o mesmo CIGAM (ver modelo-produto.md secao 3).
   */
  codigoCigam?: string | null;
  nome: string;
  /**
   * URL amigavel em kebab-case. Gerado a partir do nome se ficar vazio.
   */
  slug: string;
  /**
   * Texto de 1 a 2 frases (planilha traz texto longo).
   */
  subtitulo?: string | null;
  /**
   * Chamada do produto. Com o nome, e a primeira chamada da PDP.
   */
  headline?: string | null;
  descricaoCurta?: string | null;
  descricaoCompleta?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  beneficios?: string[] | null;
  idealPara?: string[] | null;
  diferenciais?: string[] | null;
  especificacoes?:
    | {
        rotulo: string;
        valor: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    titleTag?: string | null;
    metaDescription?: string | null;
    /**
     * Lista de termos (a planilha traz separados por virgula).
     */
    palavrasChave?: string[] | null;
    altTextPrincipal?: string | null;
  };
  /**
   * INTERNO. Nao exibir no site. Por que o produto vende.
   */
  argumentoComercial?: string | null;
  /**
   * Ate 3. A PRIMEIRA e a principal (define URL e breadcrumb).
   */
  categorias: (number | Categoria)[];
  /**
   * Fonte da verdade do eco (planilha). So as linhas Green sao ecologicas.
   */
  ecologico?: boolean | null;
  /**
   * Marcados com "OK" na planilha.
   */
  selos?: {
    livreDeBpa?: boolean | null;
    usoMicroondas?: boolean | null;
    usoLavaLoucas?: boolean | null;
    recicladoTotal?: boolean | null;
    logisticaReversa?: boolean | null;
    usoPermanente?: boolean | null;
    reducaoCo2?: boolean | null;
    fonteRenovavel?: boolean | null;
    designCircular?: boolean | null;
    upcycling?: boolean | null;
    fibraNatural?: boolean | null;
    reciclavel?: boolean | null;
    reducaoPlastico?: boolean | null;
  };
  cores?:
    | {
        nome: string;
        /**
         * Cor em hexadecimal, ex.: #1a2b3c (opcional).
         */
        hex?: string | null;
        /**
         * Foto na cor.
         */
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Galeria do produto. A primeira e a principal.
   */
  imagens?: (number | Media)[] | null;
  imagemAmbientada?: (number | null) | Media;
  /**
   * Opcional. Link de video exibido na PDP.
   */
  videoUrl?: string | null;
  logistica?: {
    ncm?: string | null;
    dimensoes?: string | null;
    pesoUnitario?: string | null;
    materiaPrima?: string | null;
    modeloCaixaMaster?: string | null;
    qtdPorCaixa?: number | null;
    dimensoesCaixaMaster?: string | null;
    pesoCaixaMaster?: string | null;
  };
  impressao?: {
    metodos?: string | null;
    areaTransfer?: string | null;
    areaTampografia?: string | null;
    areaSerigrafia?: string | null;
    sleeve?: string | null;
  };
  canais?: {
    site?: boolean | null;
    tabelaRevenda?: boolean | null;
    tabelaB2B?: boolean | null;
  };
  /**
   * Faixa exibida no catalogo. O preco exato vem do CRM.
   */
  faixaPreco?: ('ate-3-99' | '4-a-15' | 'acima-de-15') | null;
  /**
   * Faixas da home onde o produto aparece.
   */
  destaques?: ('destaque' | 'mais-vendido' | 'lancamento')[] | null;
  /**
   * Origem: CRM (Leads2b) -> ERP. Placeholder ate a integracao (S03-09). Nao editar como fonte da verdade.
   */
  crm?: {
    /**
     * Preco unitario (BRL). Vem do CRM.
     */
    preco?: number | null;
    /**
     * Saldo em estoque. Vem do CRM.
     */
    estoque?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nome: string;
  /**
   * URL amigavel em kebab-case. Gerado a partir do nome se ficar vazio.
   */
  slug: string;
  /**
   * Ecologicos ficam agrupadas no topo da lista.
   */
  grupo: 'ecologicos' | 'geral';
  /**
   * Ordem de exibicao (menor primeiro).
   */
  ordem?: number | null;
  /**
   * Icone da categoria (grade estilo iFood na home).
   */
  icone?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  titulo: string;
  subtitulo?: string | null;
  cta?: string | null;
  href?: string | null;
  imagem?: (number | null) | Media;
  posicao: 'carrossel' | 'mini';
  ativo?: boolean | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campanhas".
 */
export interface Campanha {
  id: number;
  nome: string;
  /**
   * URL amigavel em kebab-case. Gerado a partir do nome se ficar vazio.
   */
  slug: string;
  /**
   * Mes ou periodo, ex.: Maio.
   */
  mes?: string | null;
  chamada?: string | null;
  imagem?: (number | null) | Media;
  /**
   * Conteudo da landing page da campanha.
   */
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Produtos em destaque na campanha.
   */
  produtos?: (number | Produto)[] | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titulo: string;
  /**
   * URL amigavel em kebab-case. Gerado a partir do nome se ficar vazio.
   */
  slug: string;
  resumo?: string | null;
  data: string;
  autor?: string | null;
  capa?: (number | null) | Media;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  cliente: string;
  titulo: string;
  /**
   * URL amigavel em kebab-case. Gerado a partir do nome se ficar vazio.
   */
  slug: string;
  segmento?: string | null;
  resumo?: string | null;
  /**
   * Logo do cliente.
   */
  logo?: (number | null) | Media;
  imagem?: (number | null) | Media;
  depoimento?: {
    texto?: string | null;
    autor?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imprensa".
 */
export interface Imprensa {
  id: number;
  titulo: string;
  veiculo: string;
  data: string;
  resumo?: string | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revendedores".
 */
export interface Revendedore {
  id: number;
  empresa: string;
  nomeFantasia?: string | null;
  cnpj?: string | null;
  inscricaoEstadual?: string | null;
  responsavel?: string | null;
  telefone?: string | null;
  whatsapp?: string | null;
  site?: string | null;
  /**
   * Obrigatorio para ativar. Define a tabela de preco que o revendedor ve.
   */
  nivel?: ('1' | '2' | '3' | '4') | null;
  /**
   * Aprovar e atribuir a tabela sao o mesmo passo: nao da para ativar sem nivel.
   */
  ativo?: boolean | null;
  enderecoEntrega?: {
    logradouro?: string | null;
    bairro?: string | null;
    cidade?: string | null;
    uf?: string | null;
    cep?: string | null;
  };
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'revendedores';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'campanhas';
        value: number | Campanha;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'imprensa';
        value: number | Imprensa;
      } | null)
    | ({
        relationTo: 'revendedores';
        value: number | Revendedore;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'revendedores';
        value: number | Revendedore;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'revendedores';
        value: number | Revendedore;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  codigoSite?: T;
  codigoCigam?: T;
  nome?: T;
  slug?: T;
  subtitulo?: T;
  headline?: T;
  descricaoCurta?: T;
  descricaoCompleta?: T;
  beneficios?: T;
  idealPara?: T;
  diferenciais?: T;
  especificacoes?:
    | T
    | {
        rotulo?: T;
        valor?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titleTag?: T;
        metaDescription?: T;
        palavrasChave?: T;
        altTextPrincipal?: T;
      };
  argumentoComercial?: T;
  categorias?: T;
  ecologico?: T;
  selos?:
    | T
    | {
        livreDeBpa?: T;
        usoMicroondas?: T;
        usoLavaLoucas?: T;
        recicladoTotal?: T;
        logisticaReversa?: T;
        usoPermanente?: T;
        reducaoCo2?: T;
        fonteRenovavel?: T;
        designCircular?: T;
        upcycling?: T;
        fibraNatural?: T;
        reciclavel?: T;
        reducaoPlastico?: T;
      };
  cores?:
    | T
    | {
        nome?: T;
        hex?: T;
        imagem?: T;
        id?: T;
      };
  imagens?: T;
  imagemAmbientada?: T;
  videoUrl?: T;
  logistica?:
    | T
    | {
        ncm?: T;
        dimensoes?: T;
        pesoUnitario?: T;
        materiaPrima?: T;
        modeloCaixaMaster?: T;
        qtdPorCaixa?: T;
        dimensoesCaixaMaster?: T;
        pesoCaixaMaster?: T;
      };
  impressao?:
    | T
    | {
        metodos?: T;
        areaTransfer?: T;
        areaTampografia?: T;
        areaSerigrafia?: T;
        sleeve?: T;
      };
  canais?:
    | T
    | {
        site?: T;
        tabelaRevenda?: T;
        tabelaB2B?: T;
      };
  faixaPreco?: T;
  destaques?: T;
  crm?:
    | T
    | {
        preco?: T;
        estoque?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  grupo?: T;
  ordem?: T;
  icone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  cta?: T;
  href?: T;
  imagem?: T;
  posicao?: T;
  ativo?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campanhas_select".
 */
export interface CampanhasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  mes?: T;
  chamada?: T;
  imagem?: T;
  conteudo?: T;
  produtos?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  data?: T;
  autor?: T;
  capa?: T;
  conteudo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  cliente?: T;
  titulo?: T;
  slug?: T;
  segmento?: T;
  resumo?: T;
  logo?: T;
  imagem?: T;
  depoimento?:
    | T
    | {
        texto?: T;
        autor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imprensa_select".
 */
export interface ImprensaSelect<T extends boolean = true> {
  titulo?: T;
  veiculo?: T;
  data?: T;
  resumo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revendedores_select".
 */
export interface RevendedoresSelect<T extends boolean = true> {
  empresa?: T;
  nomeFantasia?: T;
  cnpj?: T;
  inscricaoEstadual?: T;
  responsavel?: T;
  telefone?: T;
  whatsapp?: T;
  site?: T;
  nivel?: T;
  ativo?: T;
  enderecoEntrega?:
    | T
    | {
        logradouro?: T;
        bairro?: T;
        cidade?: T;
        uf?: T;
        cep?: T;
      };
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}